-- lua/plugins/rose-pine.lua
return {
  "rose-pine/neovim",
  name = "rose-pine",
  lazy = false,
  priority = 1001,

  opts = {
    variant = "main",
    dark_variant = "main",
    styles = {
      italic = true,
      bold = true,
      transparency = true,
    },
    groups = {
      border = "gold",
      link = "iris",
      panel = "surface",

      error = "love",
      hint = "iris",
      info = "foam",
      note = "pine",
      todo = "rose",
      warn = "gold",

      git_add = "foam",
      git_change = "rose",
      git_delete = "love",
      git_dirty = "rose",
      git_ignore = "muted",
      git_merge = "iris",
      git_rename = "pine",
      git_stage = "iris",
      git_text = "rose",
      git_untracked = "subtle",

      h1 = "iris",
      h2 = "foam",
      h3 = "rose",
      h4 = "gold",
      h5 = "pine",
      h6 = "foam",
    },
    highlight_groups = {
      TelescopeBorder = { fg = "highlight_high", bg = "none" },
      TelescopeNormal = { bg = "none" },
      TelescopeResultsNormal = { fg = "subtle", bg = "none" },
      TelescopePreviewBorder = { fg = "rose" },
      TelescopePromptBorder = { fg = "iris" },
      TelescopeSelectionCaret = { bg = "rose", fg = "rose" },
      NoicePopupmenu = { bg = "base" },
      NoicePopupmenuBorder = { bg = "base" },
      NoiceCmdlinePopup = { bg = "base" },
      NoiceCmdlinePopupBorder = { bg = "base" },
      BlinkCmpMenu = { fg = "gold"  },
      BlinkCmpMenuBorder = { fg = "pine" },
      BlinkCmpLabel = { fg = "iris" },
      BlinkCmpKind = { fg = "love" },
      PmenuKind = { fg = "love" },
      BlinkCmpDoc = { bg = "base" },
      BlinkCmpDocBorder = { bg = "base"},
      BlinkCmpDocSeparator = { bg = "base"},
      Visual = { fg = "rose" },
      FloatBorder = { fg = "pine" },
      BlinkCmpSignatureHelpActiveParameter = { bg = "base", },
      BlinkCmpGhostText = { fg = "subtle" },
      ColorColumn = { bg = "none" },
      WinSeparator = { fg = "gold" },
      IncSearch = { fg = "foam", bg = "subtle", bold = true },
      Subsitute = { fg = "rose" },
      LineNr = { fg = "subtle" },
      CursorLineNr = { fg = "rose", bold = true },
      Whitespace = { fg = "iris" },
      WinBar = { bg = "none" },
      CursorLine = { bg = "none" },
      CurSearch = { fg = "text", bg = "leaf", inherit = false },
      Search = { fg = "text", bg = "leaf", blend = 20, inherit = false },
      MiniFilesBorder = { fg = "subtle" },
      MiniFilesBorderModified = { fg = "foam" },
      MiniFilesCursorLine = { fg = "text", bold = true },
      MiniFilesNormal = { fg = "subtle" },
      MiniFilesFile = { fg = "subtle" },
      MiniFilesTitle = { bg = "base", fg = "text", italic = true },
      MiniFilesTitleFocused = { bg = "base", fg = "gold", bold = true, italic = true },
      WhichKeyBorder = { fg = "foam" },
      Variable = { bold = true },
      Folded = { fg = "muted", italic = true },
      FoldColumn = { fg = "gold" },
      FilePath = { fg = "foam", bg = "base", italic = true },
      LspStatus = { fg = "iris" },
      Rose = { fg = "rose", bg = "base" },
      Esor = { fg = "base", bg = "rose" },
    }
  },

  config = function(_, opts)
    require("rose-pine").setup(opts)
    vim.cmd("colorscheme rose-pine-main")
  end,
}
